version: '3.8'

services:
  ratelimit:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=${ENV}
    volumes:
      - .:/app
      - logvolume01:/var/log
    command: "./ratelimit"

volumes:
  logvolume01: {}
